"""Add VIP booking details fields

Revision ID: 0578f58cb790
Revises: 4b30806959b3
Create Date: 2026-02-21 14:10:37.402634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0578f58cb790'
down_revision: Union[str, Sequence[str], None] = '4b30806959b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vip_bookings', sa.Column('zone', sa.String(length=100), nullable=True))
    op.add_column('vip_bookings', sa.Column('package', sa.String(length=100), nullable=True))
    op.add_column('vip_bookings', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('vip_bookings', sa.Column('bottle_preferences', sa.Text(), nullable=True))
    op.add_column('vip_bookings', sa.Column('special_requests', sa.Text(), nullable=True))
    op.alter_column('vip_bookings', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vip_bookings', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('vip_bookings', 'special_requests')
    op.drop_column('vip_bookings', 'bottle_preferences')
    op.drop_column('vip_bookings', 'total_price')
    op.drop_column('vip_bookings', 'package')
    op.drop_column('vip_bookings', 'zone')
    # ### end Alembic commands ###
