"""Initial schema with all tables

Revision ID: 4b30806959b3
Revises: 
Create Date: 2026-02-21 13:23:02.165627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b30806959b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aftermovies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('requests_enabled', sa.Boolean(), nullable=True),
    sa.Column('current_event_id', sa.String(length=36), nullable=True),
    sa.Column('loyalty_qr_version', sa.Integer(), nullable=True),
    sa.Column('welcome_content', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('consent_type', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_logs_user_id'), 'consent_logs', ['user_id'], unique=False)
    op.create_table('djs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('soundcloud_url', sa.String(length=500), nullable=True),
    sa.Column('spotify_url', sa.String(length=500), nullable=True),
    sa.Column('is_resident', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_qr_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=False),
    sa.Column('coins_reward', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_index(op.f('ix_event_qr_codes_event_id'), 'event_qr_codes', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_qr_codes_is_active'), 'event_qr_codes', ['is_active'], unique=False)
    op.create_table('event_qr_scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('qr_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('coins_earned', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_id', 'user_id', name='unique_scan_per_user')
    )
    op.create_index(op.f('ix_event_qr_scans_qr_id'), 'event_qr_scans', ['qr_id'], unique=False)
    op.create_index(op.f('ix_event_qr_scans_user_id'), 'event_qr_scans', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('venue_address', sa.String(length=500), nullable=True),
    sa.Column('lineup', sa.JSON(), nullable=True),
    sa.Column('ticket_categories', sa.JSON(), nullable=True),
    sa.Column('selected_djs', sa.JSON(), nullable=True),
    sa.Column('xceed_ticket_url', sa.String(length=500), nullable=True),
    sa.Column('banner_image', sa.String(length=500), nullable=True),
    sa.Column('gallery_visible', sa.Boolean(), nullable=True),
    sa.Column('aftermovie_visible', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_table('free_entry_vouchers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by', sa.String(length=36), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_free_entry_vouchers_user_id'), 'free_entry_vouchers', ['user_id'], unique=False)
    op.create_table('loyalty_checkins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('qr_version', sa.Integer(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('checked_in_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', 'qr_version', name='unique_checkin_per_event')
    )
    op.create_index(op.f('ix_loyalty_checkins_event_id'), 'loyalty_checkins', ['event_id'], unique=False)
    op.create_index(op.f('ix_loyalty_checkins_user_id'), 'loyalty_checkins', ['user_id'], unique=False)
    op.create_table('loyalty_rewards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reward_type', sa.String(length=100), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_rewards_user_id'), 'loyalty_rewards', ['user_id'], unique=False)
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_transactions_user_id'), 'loyalty_transactions', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('events', sa.Boolean(), nullable=True),
    sa.Column('promotions', sa.Boolean(), nullable=True),
    sa.Column('song_requests', sa.Boolean(), nullable=True),
    sa.Column('friends', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notifications_sent',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('sent_by', sa.String(length=36), nullable=True),
    sa.Column('recipients_count', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sizes_available', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referrer_id', sa.String(length=36), nullable=False),
    sa.Column('referred_id', sa.String(length=36), nullable=False),
    sa.Column('referrer_points', sa.Integer(), nullable=True),
    sa.Column('referred_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_referred_id'), 'referrals', ['referred_id'], unique=True)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('friends', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('firebase_uid', sa.String(length=255), nullable=True),
    sa.Column('apple_id', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('push_token', sa.String(length=500), nullable=True),
    sa.Column('push_token_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_id'),
    sa.UniqueConstraint('firebase_uid'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('delivery_method', sa.String(length=100), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_event_id'), 'photos', ['event_id'], unique=False)
    op.create_table('song_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('song_title', sa.String(length=255), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('song_title_normalized', sa.String(length=255), nullable=True),
    sa.Column('artist_name_normalized', sa.String(length=255), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('voters', sa.JSON(), nullable=True),
    sa.Column('requesters', sa.JSON(), nullable=True),
    sa.Column('times_requested', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejection_label', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_requests_artist_name_normalized'), 'song_requests', ['artist_name_normalized'], unique=False)
    op.create_index(op.f('ix_song_requests_event_id'), 'song_requests', ['event_id'], unique=False)
    op.create_index(op.f('ix_song_requests_song_title_normalized'), 'song_requests', ['song_title_normalized'], unique=False)
    op.create_index(op.f('ix_song_requests_status'), 'song_requests', ['status'], unique=False)
    op.create_index(op.f('ix_song_requests_user_id'), 'song_requests', ['user_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('ticket_code', sa.String(length=50), nullable=False),
    sa.Column('qr_data', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_code')
    )
    op.create_index(op.f('ix_tickets_event_id'), 'tickets', ['event_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.create_table('vip_bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vip_bookings_event_id'), 'vip_bookings', ['event_id'], unique=False)
    op.create_index(op.f('ix_vip_bookings_status'), 'vip_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_vip_bookings_user_id'), 'vip_bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vip_bookings_user_id'), table_name='vip_bookings')
    op.drop_index(op.f('ix_vip_bookings_status'), table_name='vip_bookings')
    op.drop_index(op.f('ix_vip_bookings_event_id'), table_name='vip_bookings')
    op.drop_table('vip_bookings')
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_event_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_song_requests_user_id'), table_name='song_requests')
    op.drop_index(op.f('ix_song_requests_status'), table_name='song_requests')
    op.drop_index(op.f('ix_song_requests_song_title_normalized'), table_name='song_requests')
    op.drop_index(op.f('ix_song_requests_event_id'), table_name='song_requests')
    op.drop_index(op.f('ix_song_requests_artist_name_normalized'), table_name='song_requests')
    op.drop_table('song_requests')
    op.drop_index(op.f('ix_photos_event_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_table('notifications_sent')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_loyalty_transactions_user_id'), table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_rewards_user_id'), table_name='loyalty_rewards')
    op.drop_table('loyalty_rewards')
    op.drop_index(op.f('ix_loyalty_checkins_user_id'), table_name='loyalty_checkins')
    op.drop_index(op.f('ix_loyalty_checkins_event_id'), table_name='loyalty_checkins')
    op.drop_table('loyalty_checkins')
    op.drop_index(op.f('ix_free_entry_vouchers_user_id'), table_name='free_entry_vouchers')
    op.drop_table('free_entry_vouchers')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_event_qr_scans_user_id'), table_name='event_qr_scans')
    op.drop_index(op.f('ix_event_qr_scans_qr_id'), table_name='event_qr_scans')
    op.drop_table('event_qr_scans')
    op.drop_index(op.f('ix_event_qr_codes_is_active'), table_name='event_qr_codes')
    op.drop_index(op.f('ix_event_qr_codes_event_id'), table_name='event_qr_codes')
    op.drop_table('event_qr_codes')
    op.drop_table('djs')
    op.drop_index(op.f('ix_consent_logs_user_id'), table_name='consent_logs')
    op.drop_table('consent_logs')
    op.drop_table('app_settings')
    op.drop_table('aftermovies')
    # ### end Alembic commands ###
